In [3]:
import numpy as np
import pandas as pd

In [ ]:
## Series of 1-D array

In [5]:
s = pd.Series([10,20,30,40])

In [6]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [10]:
pop = pd.Series([1444,1393,323,278],
                index =["India","China","USA","Indonesia"],
                name = "Population_millions"
               )

In [11]:
print(pop)

India        1444
China        1393
USA           323
Indonesia     278
Name: Population_millions, dtype: int64

In [12]:
print(pop[pop > 500])

India    1444
China    1393
Name: Population_millions, dtype: int64

In [17]:
q1 = pd.Series({"Laptops":120,"Phones":340 ,"Tablets":177})
q2 = pd.Series({"Phones":44,"Laptops":474,"Watches":73})
print(q1 + q2)

Laptops    594.0
Phones     384.0
Tablets      NaN
Watches      NaN
dtype: float64

In [ ]:
## Data Frame

In [67]:
df = pd.DataFrame({
    "name": ["Ash","Bill","Chen","Diya","Evan"],
    "dept": ["IT","HR","IT","FIN","HR"],
    "salary" : [52000,48000,47999,75000,50000],
    "city": [ "Delhi","Mumbai","Surat","Agra", "Delhi"]
})

In [68]:
print(df)

   name dept  salary    city
0   Ash   IT   52000   Delhi
1  Bill   HR   48000  Mumbai
2  Chen   IT   47999   Surat
3  Diya  FIN   75000    Agra
4  Evan   HR   50000   Delhi

In [69]:
print(df.shape)
print(list(df.columns))
df.info()
df.describe()

(5, 4)
['name', 'dept', 'salary', 'city']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   salary  5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

             salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [70]:
raw = pd.DataFrame({
    "Order_id" : ["1001","102","103"],
    "amount" : ["2500","1800","3200"]
})

In [71]:
print(raw["amount"].sum())

250018003200

In [72]:
clean = raw.copy()

In [73]:
clean["Order_id"] = pd.to_numeric(clean["Order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [74]:
print(clean["amount"].sum())

7500

In [75]:
df

   name dept  salary    city
0   Ash   IT   52000   Delhi
1  Bill   HR   48000  Mumbai
2  Chen   IT   47999   Surat
3  Diya  FIN   75000    Agra
4  Evan   HR   50000   Delhi

In [76]:
people = df.set_index("name")

In [77]:
people

     dept  salary    city
name
Ash    IT   52000   Delhi
Bill   HR   48000  Mumbai
Chen   IT   47999   Surat
Diya  FIN   75000    Agra
Evan   HR   50000   Delhi

In [78]:
print(people.loc["Ash"],["Chena"])

dept         IT
salary    52000
city      Delhi
Name: Ash, dtype: object ['Chena']

In [79]:
print(people.loc[["Ash"],["salary"]])

      salary
name
Ash    52000

In [80]:
print(people.iloc[1])

dept          HR
salary     48000
city      Mumbai
Name: Bill, dtype: object

In [81]:
print(people.iloc[0:3, [0, 2]])

     dept    city
name
Ash    IT   Delhi
Bill   HR  Mumbai
Chen   IT   Surat

In [86]:
print(people[people["salary"]<49000])

     dept  salary    city
name
Bill   HR   48000  Mumbai
Chen   IT   47999   Surat

In [89]:
print(people[(people["dept"] == "IT") & (people["salary"] < 49000)])

     dept  salary   city
name
Chen   IT   47999  Surat

In [102]:
print(people.query('dept == "IT" and salary < 49000'))

     dept  salary   city
name
Chen   IT   47999  Surat

In [ ]:
## Missing Data

In [93]:
messy = pd.DataFrame({
    "product" : ["Pen","Book","Bag","Lamp","Mug"],
    "price" : [20,np.nan,850,1200,np.nan],
    "rating": [4.1 ,4.5,np.nan,4.5,3.0]
})

In [94]:
messy

  product   price  rating
0     Pen    20.0     4.1
1    Book     NaN     4.5
2     Bag   850.0     NaN
3    Lamp  1200.0     4.5
4     Mug     NaN     3.0

In [95]:
messy.isna().sum()

product    0
price      2
rating     1
dtype: int64

In [96]:
filled = messy.copy()

In [98]:
filled ["price"] = filled["price"].fillna(filled["price"].mean())

In [99]:
filled ["rating"] = filled["rating"].fillna(filled["rating"].median())

In [100]:
print(filled)

  product   price  rating
0     Pen    20.0     4.1
1    Book   690.0     4.5
2     Bag   850.0     4.3
3    Lamp  1200.0     4.5
4     Mug   690.0     3.0